- name: Register as user with password and auto-subscribe to available content.
  redhat_subscription:
    state: present
    username: "{{vault_rhnUserID}}"
    password: "{{vault_rhnUserPass}}"
    pool_ids: "{{vault_pool_id}}"

- name: Disable all repositories except rhel-7-server-rhvh-4-rpms
  shell: |
  subscription-manager repos \
    --disable='*' \
    --enable=rhel-7-server-rpms \
    --enable=rhel-7-server-rhv-4-mgmt-agent-rpms \
    --enable=rhel-7-server-ansible-2-rpms
  


