- name: update Hosts file 
  blockinfile:
      path: /etc/hosts
      backup: yes # not required. Create a backup file including the timestamp information so you can get the original file back if you somehow clobbered it incorrectly.
      marker: ----Gluster---- # {mark ANSIBLE MANAGED BLOCK} # not required. The marker line template. "{mark}" will be replaced with the values in marker_begin (default="BEGIN") and marker_end (default="END").
      state: present # not required. choices: absent;present. Whether the block should be there or not.
      block:  |
        192.168.1.201      rhev01.darleyhome.com gluster01
        192.168.1.202      rhev02.darleyhome.com gluster02

- name: Setup Gluster repo
  blockinfile:
      path: /etc/yum.repos.d/Gluster.repo # required. The file to modify.,Before 2.3 this option was only usable as I(dest), I(destfile) and I(name).
      create: yes # not required. Create a new file if it doesn't exist.
      state: present # not required. choices: absent;present. Whether the block should be there or not.
      block: |
        [gluster7]
        name=Gluster 7
        baseurl=http://mirror.centos.org/centos/7/storage/x86_64/gluster-7/
        gpgcheck=0
        enabled=1 

- name: Install Gluster server packages
  yum:
    name: glusterfs-server
    state: latest

