- name: install the Cockpit 
  yum:
    name: cockpit-ovirt-dashboard
    state: latest

- name: enable Cockpit.socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes

- name:
  firewalld:
    service: cockpit
    permanent: true
    state: enabled
    